### ISSUE TITLE
[리팩토링] Session DB에서 제거, User 캐싱

### ISSUE THREAD

**Issue by BambooKim** [KHUCapston-concoder/Backend#86]
## 🥞 요약
채팅을 칠 때마다 DB를 통해 User와 session을 select를 통해 조회하는 것을 로그를 통해 확인했다.

채팅 시마다 DB에 쿼리를 날리는 것은 좋지 않은 설계이다.

채팅 뿐만 아니라 회의실 입장 등 여러 곳에서 RDBMS로 쿼리를 날리고 있다.

Session, Room, User 등 임시로 필요한 데이터를 RDBMS에 저장하고 메소드를 호출할 때마다 쿼리를 날리는 것은 비효율적이다.

## 📌 해야할 일
- [x] Session, Room, User를 사용하는 메소드 파악. (Service 계층 및 Controller 계층)
- [x] Session 엔티티 제거
- [ ] 엔티티가 아닌 다른 방법으로 해당 데이터를 관리할 방법 찾기

**Comment by BambooKim** [comment]
채팅 뿐만 아니라 회의실 입장 등 여러 곳에서 RDBMS로 쿼리를 날리고 있다.

Session, Room, User 등 임시로 필요한 데이터를 RDBMS에 저장하고 메소드를 호출할 때마다 쿼리를 날리는 것은 비효율적이다.

## TODO

- [ ] Session, Room, User를 사용하는 메소드 파악. (Service 계층 및 Controller 계층)
- [ ] 엔티티가 아닌 다른 방법으로 해당 데이터를 관리할 방법 찾기

**Comment by BambooKim** [comment]
## 진행사항
### `Session` Entity 제거
`Session`과 `User`가 중복된 역할을 하여 `User` 엔티티만 사용하는 것으로 통합함.
## 변경사항
### 캐시 사용안 변경
캐시는 다음과 같은 특성을 가질 때 사용하는 것이 좋다.
* 변경이 잘 일어나지 않는 데이터
* 실시간으로 일관성이 중요하지 않은 데이터
`Room`은 다음과 같은 문제점이 있다.
* 사용자 입장이 발생할 때마다 `Room`-`User` 관계 추가와 같은 데이터 변경이 발생한다.
* 실시간 일관성이 중요하다.
  * DB-Cache간 일관성 문제가 발생할 수 있다.
`User`는 현재 데이터 변경이 빈번하지는 않지만 다음의 문제점이 있다.
* 역시 실시간 일관성이 중요하다.
  * DB-Cache간 일관성 문제가 발생할 수 있다.

특히 Entity는 영속성 컨텍스트를 통해 관리되는데, Entity 자체를 Cache에 저장하면 캐시 일관성 문제가 커진다.

## 추후 방향
캐시가 가장 필요한 부분은 다음과 같다.
* ChattingService에서, 사용자가 채팅 입력 시 발신인의 정보를 조회해야 한다.
### 캐시 사용 전략
* ChattingService에서 사용자 정보 조회 시 엔티티를 직접 조회하지 않고 `User` DTO를 조회하여 사용한다. **(Read)**
  * Cache Hit - 그대로 사용한다.
  * Cache Miss - DB에서 조회하여 DTO로 변환하여 캐싱하고 사용한다. **(Create)**
* 사용자 퇴장 시 DB에서 정보를 삭제할 때 캐시에서도 함께 삭제한다. **(Delete)**
### 일관성 문제 해결 전략 **(Update)**
`User` 엔티티에서 변경될 수 있는 정보는 현재 다음과 같다.
  * `Name` - 채팅방에서 사용 중인 이름
  * `Room` - 참여 중인 채팅방

아래와 같은 작업이 필요하다.
* 데이터 Update 시마다 캐시된 데이터를 파기시켜 Cache Miss를 유발한다.
